server:
  port: 8081
spring:
  application:
    name: workflow-web

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flow_eda?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: yy3908533
    hikari:
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
mybatis:
  type-handlers-package: com.lowcode.workflow.web.handler
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    com.lowcode.workflow.web.node.data.mapper: debug


dubbo:
  application:
    name: workflow-web
    qos-enable: false
    qos-accept-foreign-ip: false
  registry:
    protocol: dubbo
    address: nacos://localhost:8848
    username: nacos
    password: nacos
  protocol:
    name: dubbo
    port: 20881
  consumer:
    check: false
    timeout: 5000
    retries: 0